/* Generated By:JJTree: Do not edit this line. ASTand_clause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTand_clause extends SimpleNode {
  public ASTand_clause(int id) {
    super(id);
  }

  public ASTand_clause(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=33039d57d826bea6d9e971aef0b5d5b8 (do not edit this line) */
