/* Generated By:JJTree: Do not edit this line. ASTcomparison.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcomparison extends SimpleNode {
  public ASTcomparison(int id) {
    super(id);
  }

  public ASTcomparison(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ceb4b9ce9e597b390e50304ebc73a779 (do not edit this line) */
