/* Generated By:JJTree: Do not edit this line. ASTfor_explicit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfor_explicit extends SimpleNode {
  public ASTfor_explicit(int id) {
    super(id);
  }

  public ASTfor_explicit(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=db0d5b6fc11a04c185aca52a7b22e2ea (do not edit this line) */
