/* Generated By:JJTree: Do not edit this line. ASTfor_implicit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfor_implicit extends SimpleNode {
  public ASTfor_implicit(int id) {
    super(id);
  }

  public ASTfor_implicit(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=efc560a88aff61bd6b7ade8283b2ca76 (do not edit this line) */
