/* Generated By:JJTree: Do not edit this line. ASTGreateEq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGreateEq extends SimpleNode {
  public ASTGreateEq(int id) {
    super(id);
  }

  public ASTGreateEq(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f5c5d0189f23f16aaa04c65108f5fd9b (do not edit this line) */
