/* Generated By:JJTree: Do not edit this line. ASTisatype.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTisatype extends SimpleNode {
  public ASTisatype(int id) {
    super(id);
  }

  public ASTisatype(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6b3f76ef5c02e0de54e0f12b317a8078 (do not edit this line) */
