/* Generated By:JJTree: Do not edit this line. ASTIsNotIn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIsNotIn extends SimpleNode {
  public ASTIsNotIn(int id) {
    super(id);
  }

  public ASTIsNotIn(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8efe7f4d13a89d014a9b855e15b0451b (do not edit this line) */
