/* Generated By:JJTree: Do not edit this line. ASTIsIn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIsIn extends SimpleNode {
  public ASTIsIn(int id) {
    super(id);
  }

  public ASTIsIn(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=36fbf460c77d4aa4df3f1e5ecfc7af04 (do not edit this line) */
