/* Generated By:JJTree: Do not edit this line. ASTmore_expressions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmore_expressions extends SimpleNode {
  public ASTmore_expressions(int id) {
    super(id);
  }

  public ASTmore_expressions(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f3bf75733b25f5db551eace1eda2441c (do not edit this line) */
