/* Generated By:JJTree: Do not edit this line. ASTmodulo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmodulo extends SimpleNode {
  public ASTmodulo(int id) {
    super(id);
  }

  public ASTmodulo(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ebe78b793935c546c89e583efcb36dc2 (do not edit this line) */
