/* Generated By:JJTree: Do not edit this line. ASTmore_products.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmore_products extends SimpleNode {
  public ASTmore_products(int id) {
    super(id);
  }

  public ASTmore_products(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5332c6ab91e95b550fe9c7d1bde80b65 (do not edit this line) */
