/* Generated By:JJTree: Do not edit this line. ASTnot_clause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnot_clause extends SimpleNode {
  public ASTnot_clause(int id) {
    super(id);
  }

  public ASTnot_clause(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e5800b1bd867f894c67e4a4d47c2ed25 (do not edit this line) */
