/* Generated By:JJTree: Do not edit this line. ASTNotComp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNotComp extends SimpleNode {
  public ASTNotComp(int id) {
    super(id);
  }

  public ASTNotComp(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bcc4c3298e35a11efdbcfcfddb1177e8 (do not edit this line) */
