/* Generated By:JJTree: Do not edit this line. ASToptional_parameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASToptional_parameters extends SimpleNode {
  public ASToptional_parameters(int id) {
    super(id);
  }

  public ASToptional_parameters(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f5d2d77f06a312525d00a150aad5c643 (do not edit this line) */
