/* Generated By:JJTree: Do not edit this line. ASToptional_return_value.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASToptional_return_value extends SimpleNode {
  public ASToptional_return_value(int id) {
    super(id);
  }

  public ASToptional_return_value(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=64719afc41b045ec9fadfa3616511f3f (do not edit this line) */
