/* Generated By:JJTree: Do not edit this line. ASTprintln_stat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprintln_stat extends SimpleNode {
  public ASTprintln_stat(int id) {
    super(id);
  }

  public ASTprintln_stat(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1b10577ed2ad6b7cf019e4ddb97f06b1 (do not edit this line) */
