/* Generated By:JJTree: Do not edit this line. ASTpredicate_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTpredicate_decl extends SimpleNode {
  public ASTpredicate_decl(int id) {
    super(id);
  }

  public ASTpredicate_decl(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f167dceeafa4d029dca7bfb8f55f7abf (do not edit this line) */
