/* Generated By:JJTree: Do not edit this line. ASTsubtraction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsubtraction extends SimpleNode {
  public ASTsubtraction(int id) {
    super(id);
  }

  public ASTsubtraction(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=80f286dc785fcf75f18a968a7af78dc0 (do not edit this line) */
