/* Generated By:JJTree: Do not edit this line. ASTstatement_ll.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatement_ll extends SimpleNode {
  public ASTstatement_ll(int id) {
    super(id);
  }

  public ASTstatement_ll(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9fb32f80740dc7bd2d92df5e23876d3d (do not edit this line) */
