/* Generated By:JJTree: Do not edit this line. ASTset_const.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTset_const extends SimpleNode {
  public ASTset_const(int id) {
    super(id);
  }

  public ASTset_const(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dc3d23b47a436d6c2363baf4d81eaf71 (do not edit this line) */
