/* Generated By:JJTree: Do not edit this line. ASTset_elements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTset_elements extends SimpleNode {
  public ASTset_elements(int id) {
    super(id);
  }

  public ASTset_elements(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d2b58403b3d7f343e0d6a2355096de08 (do not edit this line) */
