/* Generated By:JavaCC: Do not edit this line. HLTreeConstants.java Version 5.0 */
public interface HLTreeConstants
{
  public int JJTVOID = 0;
  public int JJTASSIGNMENT = 1;
  public int JJTEXPRESSION = 2;
  public int JJTSTATEMENT = 3;
  public int JJTSTATEMENT_LL = 4;
  public int JJTFN_CALL = 5;
  public int JJTDECLARATION = 6;
  public int JJTBODY = 7;
  public int JJTCLAUSE = 8;
  public int JJTSIMPLE_DECL = 9;
  public int JJTFN_DECL = 10;
  public int JJTSUB_DECL = 11;
  public int JJTPREDICATE_DECL = 12;
  public int JJTTYPE = 13;
  public int JJTIDENT_LIST = 14;
  public int JJTPARAM_DECLS = 15;
  public int JJTPARAM_DECL = 16;
  public int JJTIF_STAT = 17;
  public int JJTFOR_EXPLICIT = 18;
  public int JJTFOR_IMPLICIT = 19;
  public int JJTWHILE_STAT = 20;
  public int JJTRETURN_STAT = 21;
  public int JJTPRINT_STAT = 22;
  public int JJTPRINTLN_STAT = 23;
  public int JJTPARAMETERS = 24;
  public int JJTISATYPE = 25;
  public int JJTSUMATION = 26;
  public int JJTSUBTRACTION = 27;
  public int JJTPRODUCT = 28;
  public int JJTDIVISION = 29;
  public int JJTMODULO = 30;
  public int JJTSET = 31;
  public int JJTIDENTIFIER = 32;
  public int JJTNUMBER = 33;
  public int JJTSTRING = 34;
  public int JJTTRUE = 35;
  public int JJTFALSE = 36;
  public int JJTNUMTYPE = 37;
  public int JJTSTRTYPE = 38;
  public int JJTSETTYPE = 39;
  public int JJTOBJTYPE = 40;
  public int JJTLESS = 41;
  public int JJTLESSEQ = 42;
  public int JJTGREATER = 43;
  public int JJTGREATEEQ = 44;
  public int JJTNOTCOMP = 45;
  public int JJTNOTEQ = 46;
  public int JJTEQUAL = 47;
  public int JJTISIN = 48;
  public int JJTISNOTIN = 49;
  public int JJTPLUSOP = 50;


  public String[] jjtNodeName = {
    "void",
    "assignment",
    "expression",
    "statement",
    "statement_ll",
    "fn_call",
    "declaration",
    "body",
    "clause",
    "simple_decl",
    "fn_decl",
    "sub_decl",
    "predicate_decl",
    "type",
    "ident_list",
    "param_decls",
    "param_decl",
    "if_stat",
    "for_explicit",
    "for_implicit",
    "while_stat",
    "return_stat",
    "print_stat",
    "println_stat",
    "parameters",
    "isatype",
    "sumation",
    "subtraction",
    "product",
    "division",
    "modulo",
    "set",
    "Identifier",
    "Number",
    "String",
    "True",
    "False",
    "NumType",
    "StrType",
    "SetType",
    "ObjType",
    "Less",
    "LessEq",
    "Greater",
    "GreateEq",
    "NotComp",
    "NotEq",
    "Equal",
    "IsIn",
    "IsNotIn",
    "PlusOp",
  };
}
/* JavaCC - OriginalChecksum=23081cd420dba48536f422a7e1f05f2d (do not edit this line) */
