/* Generated By:JavaCC: Do not edit this line. HLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FOR = 9;
  /** RegularExpression Id. */
  int NUM = 10;
  /** RegularExpression Id. */
  int STR = 11;
  /** RegularExpression Id. */
  int SET = 12;
  /** RegularExpression Id. */
  int OBJ = 13;
  /** RegularExpression Id. */
  int ISA = 14;
  /** RegularExpression Id. */
  int FROM = 15;
  /** RegularExpression Id. */
  int TO = 16;
  /** RegularExpression Id. */
  int DO = 17;
  /** RegularExpression Id. */
  int OD = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int THEN = 21;
  /** RegularExpression Id. */
  int ELIF = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int FI = 24;
  /** RegularExpression Id. */
  int FUNCTION = 25;
  /** RegularExpression Id. */
  int SUB = 26;
  /** RegularExpression Id. */
  int PREDICATE = 27;
  /** RegularExpression Id. */
  int RETURN = 28;
  /** RegularExpression Id. */
  int END = 29;
  /** RegularExpression Id. */
  int PRINT = 30;
  /** RegularExpression Id. */
  int PRINTLN = 31;
  /** RegularExpression Id. */
  int TRUE = 32;
  /** RegularExpression Id. */
  int FALSE = 33;
  /** RegularExpression Id. */
  int NULL = 34;
  /** RegularExpression Id. */
  int LESS = 35;
  /** RegularExpression Id. */
  int LESSEQ = 36;
  /** RegularExpression Id. */
  int GREATER = 37;
  /** RegularExpression Id. */
  int GREATEREQ = 38;
  /** RegularExpression Id. */
  int NOTCOMP = 39;
  /** RegularExpression Id. */
  int EQUAL = 40;
  /** RegularExpression Id. */
  int NOTEQ = 41;
  /** RegularExpression Id. */
  int IN = 42;
  /** RegularExpression Id. */
  int NOTIN = 43;
  /** RegularExpression Id. */
  int PLUS = 44;
  /** RegularExpression Id. */
  int MINUS = 45;
  /** RegularExpression Id. */
  int PROD = 46;
  /** RegularExpression Id. */
  int DIV = 47;
  /** RegularExpression Id. */
  int MOD = 48;
  /** RegularExpression Id. */
  int AND = 49;
  /** RegularExpression Id. */
  int OR = 50;
  /** RegularExpression Id. */
  int NOT = 51;
  /** RegularExpression Id. */
  int ASSIGN = 52;
  /** RegularExpression Id. */
  int LPAREN = 53;
  /** RegularExpression Id. */
  int RPAREN = 54;
  /** RegularExpression Id. */
  int LCURLY = 55;
  /** RegularExpression Id. */
  int RCURLY = 56;
  /** RegularExpression Id. */
  int COMMA = 57;
  /** RegularExpression Id. */
  int SEMICOL = 58;
  /** RegularExpression Id. */
  int IDENTIFIER = 59;
  /** RegularExpression Id. */
  int NUMBER = 60;
  /** RegularExpression Id. */
  int STRING = 61;
  /** RegularExpression Id. */
  int OTHER = 62;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MULTI_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"for\"",
    "\"num\"",
    "\"str\"",
    "\"set\"",
    "\"obj\"",
    "\"isa\"",
    "\"from\"",
    "\"to\"",
    "\"do\"",
    "\"od\"",
    "\"while\"",
    "\"if\"",
    "\"then\"",
    "\"elif\"",
    "\"else\"",
    "\"fi\"",
    "\"function\"",
    "\"sub\"",
    "\"predicate\"",
    "\"return\"",
    "\"end\"",
    "\"print\"",
    "\"println\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"<>\"",
    "\"==\"",
    "\"!=\"",
    "\"=in\"",
    "\"!in\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<STRING>",
    "<OTHER>",
  };

}
