/* Generated By:JJTree: Do not edit this line. ASTEQUAL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEQUAL extends SimpleNode {
  public ASTEQUAL(int id) {
    super(id);
  }

  public ASTEQUAL(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=170ca81d3c5fc95adc40dfb55e169cae (do not edit this line) */
