/* Generated By:JJTree: Do not edit this line. ASTGREATER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGREATER extends SimpleNode {
  public ASTGREATER(int id) {
    super(id);
  }

  public ASTGREATER(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=35399c4e3a6270e9085f56b2e2b7e2f0 (do not edit this line) */
