/* Generated By:JJTree: Do not edit this line. ASTNOTHING.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNOTHING extends SimpleNode {
  public ASTNOTHING(int id) {
    super(id);
  }

  public ASTNOTHING(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=22dbfe96818adf4294b9b33709b0a0e3 (do not edit this line) */
