/* Generated By:JJTree: Do not edit this line. ASTNOTCOMP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNOTCOMP extends SimpleNode {
  public ASTNOTCOMP(int id) {
    super(id);
  }

  public ASTNOTCOMP(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3d9687691a541abf6290de60aacd1952 (do not edit this line) */
