/* Generated By:JJTree: Do not edit this line. ASTNUMTYPE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNUMTYPE extends SimpleNode {
  public ASTNUMTYPE(int id) {
    super(id);
  }

  public ASTNUMTYPE(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7b499f04b5f5f2dea891b01cb8d10563 (do not edit this line) */
