/* Generated By:JJTree: Do not edit this line. ASTSTRTYPE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTRTYPE extends SimpleNode {
  public ASTSTRTYPE(int id) {
    super(id);
  }

  public ASTSTRTYPE(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4dcf6cd5cf7c1c252e7543024b8ec491 (do not edit this line) */
