/* Generated By:JJTree: Do not edit this line. ASTSETTYPE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSETTYPE extends SimpleNode {
  public ASTSETTYPE(int id) {
    super(id);
  }

  public ASTSETTYPE(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bc5ec15076f12cfbc4e9a1153f9eb802 (do not edit this line) */
