/* Generated By:JavaCC: Do not edit this line. HLTreeConstants.java Version 5.0 */
public interface HLTreeConstants
{
  public int JJTVOID = 0;
  public int JJTBODY = 1;
  public int JJTCLAUSE = 2;
  public int JJTSIMPLE_DECL = 3;
  public int JJTIDENT_LIST = 4;
  public int JJTFN_DECL = 5;
  public int JJTSUB_DECL = 6;
  public int JJTPREDICATE_DECL = 7;
  public int JJTNUMTYPE = 8;
  public int JJTSTRTYPE = 9;
  public int JJTSETTYPE = 10;
  public int JJTOBJTYPE = 11;
  public int JJTPARAM_DECLS = 12;
  public int JJTPARAM_DECL = 13;
  public int JJTASSIGNMENT = 14;
  public int JJTIF_STAT = 15;
  public int JJTNOTHING = 16;
  public int JJTFOR_EXPLICIT = 17;
  public int JJTFOR_IMPLICIT = 18;
  public int JJTWHILE_STAT = 19;
  public int JJTFN_CALL = 20;
  public int JJTRETURN_STAT = 21;
  public int JJTTRUE = 22;
  public int JJTFALSE = 23;
  public int JJTPRINT = 24;
  public int JJTPRINTLN = 25;
  public int JJTPARAMETERS = 26;
  public int JJTOR = 27;
  public int JJTAND = 28;
  public int JJTNOT = 29;
  public int JJTCOMPARISON = 30;
  public int JJTLESS = 31;
  public int JJTLESSEQ = 32;
  public int JJTGREATER = 33;
  public int JJTGREATEQ = 34;
  public int JJTNOTCOMP = 35;
  public int JJTEQUAL = 36;
  public int JJTNOTEQ = 37;
  public int JJTISIN = 38;
  public int JJTNOTIN = 39;
  public int JJTISATYPE = 40;
  public int JJTNEGATE = 41;
  public int JJTSUM = 42;
  public int JJTDIFFERENCE = 43;
  public int JJTPRODUCT = 44;
  public int JJTQUOTIENT = 45;
  public int JJTREMAINDER = 46;
  public int JJTNULL = 47;
  public int JJTSET = 48;
  public int JJTIDENTIFIER = 49;
  public int JJTNUMBER = 50;
  public int JJTSTRING = 51;


  public String[] jjtNodeName = {
    "void",
    "body",
    "clause",
    "simple_decl",
    "ident_list",
    "fn_decl",
    "sub_decl",
    "predicate_decl",
    "NUMTYPE",
    "STRTYPE",
    "SETTYPE",
    "OBJTYPE",
    "param_decls",
    "param_decl",
    "assignment",
    "if_stat",
    "NOTHING",
    "for_explicit",
    "for_implicit",
    "while_stat",
    "fn_call",
    "return_stat",
    "TRUE",
    "FALSE",
    "print",
    "println",
    "parameters",
    "or",
    "and",
    "not",
    "comparison",
    "LESS",
    "LESSEQ",
    "GREATER",
    "GREATEQ",
    "NOTCOMP",
    "EQUAL",
    "NOTEQ",
    "ISIN",
    "NOTIN",
    "isatype",
    "negate",
    "sum",
    "difference",
    "product",
    "quotient",
    "remainder",
    "NULL",
    "set",
    "identifier",
    "number",
    "string",
  };
}
/* JavaCC - OriginalChecksum=66371467f20e86d5ffb52e98f742db9e (do not edit this line) */
